# Generated by Django 5.2.7 on 2025-11-16 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('requisitos', models.JSONField(blank=True, default=list)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to='categorias.categoria')),
            ],
            options={
                'ordering': ['titulo'],
                'indexes': [models.Index(fields=['slug'], name='tramites_tr_slug_780560_idx'), models.Index(fields=['activo'], name='tramites_tr_activo_cf5dad_idx'), models.Index(fields=['categoria'], name='tramites_tr_categor_ce2594_idx')],
                'unique_together': {('categoria', 'slug')},
            },
        ),
    ]
