# Generated by Django 5.2.7 on 2025-11-16 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('anio_correspondiente', models.PositiveSmallIntegerField(help_text='Año al que pertenece la clase')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('carnet', models.CharField(max_length=20, unique=True)),
                ('grupo_principal', models.CharField(max_length=20)),
                ('grupo_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('anio_actual', models.PositiveSmallIntegerField(help_text='Año que cursa actualmente')),
                ('tiene_beca', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Ej. I Semestre 2025', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='students.clase')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'clase', 'periodo')},
            },
        ),
    ]
