# Generated by Django 5.2.7 on 2025-11-16 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requisitos', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='becas', to='categorias.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionBeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Ej. I Semestre 2025', max_length=40)),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('finalizada', 'Finalizada'), ('rechazada', 'Rechazada')], default='asignada', max_length=20)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('monto_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_beca', to='students.student')),
                ('beca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='becas.beca')),
            ],
            options={
                'ordering': ('-activo', 'student__carnet', 'beca__tipo'),
                'indexes': [models.Index(fields=['student', 'activo', 'estado'], name='becas_asign_student_ecff30_idx'), models.Index(fields=['periodo'], name='becas_asign_periodo_6753b6_idx')],
                'unique_together': {('student', 'beca', 'periodo')},
            },
        ),
    ]
