# Generated by Django 5.2.7 on 2025-11-16 00:02

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(db_index=True, help_text='Código de grupo (ej. 1M1, 4T2, 5T1).', max_length=8, validators=[django.core.validators.RegexValidator('^[1-5][MT][1-2]$')])),
                ('titulo', models.CharField(max_length=180)),
                ('periodo', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('original_filename', models.CharField(max_length=255)),
                ('imagen', models.BinaryField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('group_code', 'periodo'), name='uniq_horario_activo_por_grupo_y_periodo')],
            },
        ),
    ]
